# These are supported funding model platforms

github: [traycergreek]
patreon: traycergreek
open_collective: traycergreek
ko_fi: traycergreek
tidelift: platform
custom: ['https://traycergreek.com/donate', 'https://traycergreek.com/support']
